### ISSUE TITLE
Only empty response

### ISSUE THREAD

**Issue by atluxity** [gdidentity/c-web-analytics#2]
Hey,

I only get empty responses using that Graph Query, is there anything I can do to diagnose?

**Comment by bebjakub** [comment]
Hey @atluxity,
are you sure, that you correctly filled plugin options? /wp-admin/options-general.php?page=c-web-analytics
I just checked the plugin on a production website, it works correctly.
btw. if you want more info about how the plugin fetches data from Cloudflare via GraphQL, check  https://github.com/gdidentity/c-web-analytics/blob/main/src/Api.php

Have a nice day

**Comment by atluxity** [comment]
No, I am not sure. How can I be sure, the documentation is pretty lacking and the plugin uses terms that Cloudflare does not.
What is a Site Tag?
And Frontend Domain, that is the name as shown in Cloudflare list of sites my account has?

**Comment by atluxity** [comment]
I tried using Zone ID instead of Site Tag, as this seem normal with the API, but it give me no response.

Would it not be possible to have a "Test config" button that could give some better error message if this was not filled in according to specs?

**Comment by bebjakub** [comment]
Hi,
sorry for delay
You'll find it in the Site analytics URL 
```https://dash.cloudflare.com/[ACCOUNT_ID]/web-analytics/overview?siteTag~in=[SITE_TAG]```.

**Comment by atluxity** [comment]
No worries, mate. You respond plenty of fast enough. That clue got me to success. Thank you!
I also see you implemented the clue into the plugin.

Now that it works, it looks impressive. I dont know why not more people use this plugin. Thanks for you effort! Can I buy you a beer somehow?

**Comment by bebjakub** [comment]
@atluxity Great, you are welcome. 
Thank you for reporting! :)
